### ISSUE TITLE
安装时出现了一些问题

### ISSUE THREAD

**Issue by a188037445** [ventoy/Ventoy#366]
我的系统是 debian testing，刚刚下载了最新版本的 ventoy 安装的时候，我的 kde 桌面重启了一次（桌面崩溃了），wifi 网络似乎也断开了一次（自动重连了）。

下面是程序的输出：
![Screenshot_20200731_184016](https://user-images.githubusercontent.com/46810417/89027593-55048400-d35d-11ea-89ca-ba1170f8b6d6.png)

为了测试，我又使用 `-I` 选项重新安装了一次，这次桌面没崩溃，但是网络又重连了，输出和上次一样。

我想问下是什么原因呢？

**Comment by ventoy** [comment]
我也不知道什么原因，理论上安装时只是读写磁盘，应该和网络没关系。

**Comment by a188037445** [comment]
我刚刚测试了新版1.0.19，桌面又崩溃了，下面是kde崩溃处理程序给出的信息，不知道有没有用：

可执行程序：kded5 进程号：903 信号：Segmentation fault(11) 时间：2020/8/16 08:38:37

```c++
Application: kded5 (kded5), signal: Segmentation fault
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Current thread is 1 (Thread 0x7f277bcd0800 (LWP 903))]

Thread 4 (Thread 0x7f27697fa700 (LWP 970)):
#0  0x00007f277f1934bf in __GI___poll (fds=0x7f2740004e60, nfds=1, timeout=10012) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007f277e3647ee in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f277e36490f in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f277f72690b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x00007f277f6ce89b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007f277f4f98be in QThread::exec() () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007f277f4fa988 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#7  0x00007f277f086ea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
#8  0x00007f277f19deaf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 3 (Thread 0x7f2773fff700 (LWP 911)):
#0  0x00007f277f1934bf in __GI___poll (fds=0x7f276c01aa70, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007f277e3647ee in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#2  0x00007f277e36490f in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#3  0x00007f277f72690b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#4  0x00007f277f6ce89b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007f277f4f98be in QThread::exec() () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007f277fa0f507 in  () at /lib/x86_64-linux-gnu/libQt5DBus.so.5
#7  0x00007f277f4fa988 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007f277f086ea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
#9  0x00007f277f19deaf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 2 (Thread 0x7f277aeb6700 (LWP 909)):
#0  0x00007f277f1934bf in __GI___poll (fds=0x7f277aeb5ca8, nfds=1, timeout=-1) at ../sysdeps/unix/sysv/linux/poll.c:29
#1  0x00007f277e2f6d02 in  () at /lib/x86_64-linux-gnu/libxcb.so.1
#2  0x00007f277e2f898a in xcb_wait_for_event () at /lib/x86_64-linux-gnu/libxcb.so.1
#3  0x00007f277b8a1dc0 in  () at /lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#4  0x00007f277f4fa988 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007f277f086ea7 in start_thread (arg=<optimized out>) at pthread_create.c:477
#6  0x00007f277f19deaf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 1 (Thread 0x7f277bcd0800 (LWP 903)):
[KCrash Handler]
#4  0x00007f277ed366ba in XPending () at /lib/x86_64-linux-gnu/libX11.so.6
#5  0x00007f2770158978 in  () at /usr/lib/x86_64-linux-gnu/qt5/plugins/kded_touchpad.so
#6  0x00007f2770158a22 in  () at /usr/lib/x86_64-linux-gnu/qt5/plugins/kded_touchpad.so
#7  0x00007f277f704730 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007f277f707e31 in QSocketNotifier::activated(int, QSocketNotifier::QPrivateSignal) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#9  0x00007f277f708171 in QSocketNotifier::event(QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#10 0x00007f27803e1ccf in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#11 0x00007f27803eae10 in QApplication::notify(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Widgets.so.5
#12 0x00007f277f6cfd02 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#13 0x00007f277f7274b5 in  () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#14 0x00007f277e3645fd in g_main_context_dispatch () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#15 0x00007f277e364880 in  () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#16 0x00007f277e36490f in g_main_context_iteration () at /lib/x86_64-linux-gnu/libglib-2.0.so.0
#17 0x00007f277f7268ee in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#18 0x00007f277f6ce89b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#19 0x00007f277f6d6672 in QCoreApplication::exec() () at /lib/x86_64-linux-gnu/libQt5Core.so.5
#20 0x00005567c5d581f9 in  ()
#21 0x00007f277f0c6cca in __libc_start_main (main=0x5567c5d57b10, argc=1, argv=0x7ffedb87d688, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffedb87d678) at ../csu/libc-start.c:308
#22 0x00005567c5d584fa in  ()
[Inferior 1 (process 903) detached]
```
